[project]
name = "meta-ads-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=6.0.0",
    "black>=25.12.0",
    "marimo>=0.18.4",
    "pandas>=2.3.3",
    "requests>=2.32.5",
]
